Rvp rebase 1
plctlab/riscv-binutils-gdb pull request #1
Opened 2022-07-01 09:21 UTC by Liaoshihua

2022-07-02 04:55 UTC, linsinan1995 commented on .vscode/settings.json
> +{
unnecessary file

2022-07-02 04:55 UTC, linsinan1995 commented on gas/config/tc-riscv.c
> +case 'n':
formatting

2022-07-14 01:29 UTC, pz9115 requested changes

2022-07-14 01:29 UTC, pz9115 commented on bfd/elfxx-riscv.c
> +  {"zpsf",		ISA_SPEC_CLASS_DRAFT,		0, 9,  11 },
Add additional space line.

2022-07-14 01:29 UTC, pz9115 commented on gas/testsuite/gas/riscv/insn-dsp-zbpbo.d
> +[ 	]+.*:[ 	]+.*[ 	]+clz[ 	]+a1,a2
use the caculated opcdoe instead of *

2022-07-14 01:29 UTC, pz9115 commented on gas/testsuite/gas/riscv/insn-dsp.d
> +[ 	]+.*:[ 	]+.*[ 	]+add16[ 	]+a1,a2,a3
need opcode

2022-07-14 01:29 UTC, pz9115 commented on gas/testsuite/gas/riscv/insn-dsp64-zbpbo.d
> +[ 	]+.*:[ 	]+.*[ 	]+cmix[ 	]+a1,a2,a3,a4
same, opcode required

2022-07-14 01:29 UTC, pz9115 commented on gas/testsuite/gas/riscv/rvp_csr.s
> +    csrr t0,vxsat
Is the vxsat csr in RVV?

2022-07-14 01:41 UTC, Liaoshihua commented on gas/testsuite/gas/riscv/rvp_csr.s
> +    csrr t0,vxsat
yes, the csr "vxsat" includes in RVV as well.

2022-07-15 02:21 UTC, closed without merging